name: teste_tonolucro

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  provider: ^4.3.2+2
  flutter_icons: ^1.1.0
  intl: ^0.16.1
  badges: ^1.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lib/assets/avatar.png
    - lib/assets/logo.png
    - lib/assets/contacts.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
